### ISSUE TITLE
Internal sub-navigation deployed via publishing rule

### ISSUE THREAD

**Issue by smebberson** [thememphisagency/fcbresponsive#11]
Baked into dmHTML the ability to turn on/off and then choose an entry from the site tree

**Comment by yorky001** [comment]
Used dynamic background colour based on site secondary colour.

**Comment by jonlow** [comment]
The Sub Navigation Menu rule should automatically display the **siblings** of the currently viewed page as well as the currently viewed page in an active state.

In the case of the current fcbresponsive navigation structure, the rule shouldn't be on the index pages, but the internal product pages (e.g product 1), so that the navigation shows all the other sibling products.

Since the rule is automatic (don't need to choose a navigation node), maybe this shouldn't be a rule since there are no options for a business user to select? Should it just be a new display page or a dynamic include?

**Comment by yorky001** [comment]
Changed to Included object called "Sibling Nav" as Sub Nav suggests different functionality.
